### ISSUE TITLE
Use of **const** in strict mode.

### ISSUE THREAD

**Issue by tiagoinacio** [Lanfei/gulp-file-rev#1]
I'm getting an error when using this plugin with an older version of node: 0.12.7.

Use of **const** in strict mode: gulp-file-rev/index.js - line 8.

`const PLUGIN_NAME = 'gulp-file-rev';`

If you want to use **const** and other features of ES6 you should not use strict mode, or you could change the **const** to a var **statement**.

**Comment by Lanfei** [comment]
Thank you for your reminding, I have merged your pull-request(#2), and publish a new version on npm.
